/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gmstackexample;

import javax.swing.JOptionPane;

/**
 *
 * @author gregm
 */
public class Display extends javax.swing.JFrame {

    /**
     * Creates new form Display
     */
    MyStackADT StackOfTrains = new MyStackADT();

    public Display() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddBTN = new javax.swing.JButton();
        RemoveBTN = new javax.swing.JButton();
        DisplayWagons = new javax.swing.JButton();
        FirstBTN = new javax.swing.JButton();
        RemoveAllBTN = new javax.swing.JButton();
        ListProducts = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductsTextArea = new javax.swing.JTextArea();
        ProductField = new javax.swing.JTextField();
        WagonProductField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddBTN.setText("Add Wagon");
        AddBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBTNMouseClicked(evt);
            }
        });

        RemoveBTN.setText("Remove wagon");
        RemoveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBTNActionPerformed(evt);
            }
        });

        DisplayWagons.setText("Number of wagons");
        DisplayWagons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayWagonsActionPerformed(evt);
            }
        });

        FirstBTN.setText("First Wagon");
        FirstBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstBTNActionPerformed(evt);
            }
        });

        RemoveAllBTN.setText("Remove all wagons");
        RemoveAllBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveAllBTNActionPerformed(evt);
            }
        });

        ListProducts.setText("List all products");
        ListProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListProductsActionPerformed(evt);
            }
        });

        ProductsTextArea.setColumns(20);
        ProductsTextArea.setRows(5);
        jScrollPane1.setViewportView(ProductsTextArea);

        WagonProductField.setText("Wagon Product");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RemoveBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(DisplayWagons))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(FirstBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ListProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RemoveAllBTN)))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddBTN)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(WagonProductField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WagonProductField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddBTN)
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveBTN)
                    .addComponent(DisplayWagons))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstBTN)
                    .addComponent(RemoveAllBTN))
                .addGap(18, 18, 18)
                .addComponent(ListProducts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBTNMouseClicked
        String wagonProduct = ProductField.getText().trim();

if (!wagonProduct.isEmpty()) {
    StackOfTrains.push(wagonProduct); 
    JOptionPane.showMessageDialog(this, "added succesfulyy: " + wagonProduct);//notify the end user
    ProductField.setText("");
} else {
    JOptionPane.showMessageDialog(this, "Please enter a string value for the product of said wagon.");//notify the end user
}
    }//GEN-LAST:event_AddBTNMouseClicked

    private void RemoveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBTNActionPerformed
        if (!StackOfTrains.isEmpty()) {
    Object removedWagon = StackOfTrains.pop();
    JOptionPane.showMessageDialog(this, "Removed succesfully: " + removedWagon);//notify the end user
} else {
    JOptionPane.showMessageDialog(this, "Empty nothing to remove.");//notify the end user
}
    }//GEN-LAST:event_RemoveBTNActionPerformed

    private void FirstBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstBTNActionPerformed
        if (!StackOfTrains.isEmpty()) {
    Object firstWagon = StackOfTrains.peek();
    ProductsTextArea.setText("The first wagon has: " + firstWagon);//notify the end user
} else {
    ProductsTextArea.setText("nothings found.");//notify the end user
}

    }//GEN-LAST:event_FirstBTNActionPerformed

    private void ListProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListProductsActionPerformed
        if (!StackOfTrains.isEmpty()) {
    String allProducts = StackOfTrains.displayStack();
    ProductsTextArea.setText("All : \n" + allProducts);//notify the end user
} else {
    ProductsTextArea.setText("Nothing to show");//notify the end user
}
    }//GEN-LAST:event_ListProductsActionPerformed

    private void DisplayWagonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayWagonsActionPerformed
        int numberOfWagons = StackOfTrains.size();
JOptionPane.showMessageDialog(this, "There is " + numberOfWagons + " wagons on the train.");//notify the end user

    }//GEN-LAST:event_DisplayWagonsActionPerformed

    private void RemoveAllBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveAllBTNActionPerformed
    if (!StackOfTrains.isEmpty()) {
    while (!StackOfTrains.isEmpty()) {//loop to remove all, so while tis not empty
        StackOfTrains.pop();//pop
    }//end while
    JOptionPane.showMessageDialog(this, "Removed succesfully.");//notify the end user
} else {//start else
    JOptionPane.showMessageDialog(this, "Train was alreaDY emptied.");//notify the end user
}//end else

    }//GEN-LAST:event_RemoveAllBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBTN;
    private javax.swing.JButton DisplayWagons;
    private javax.swing.JButton FirstBTN;
    private javax.swing.JButton ListProducts;
    private javax.swing.JTextField ProductField;
    private javax.swing.JTextArea ProductsTextArea;
    private javax.swing.JButton RemoveAllBTN;
    private javax.swing.JButton RemoveBTN;
    private javax.swing.JLabel WagonProductField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
